#!/usr/bin/env node
/**
 * Fetches the node catalog from the control-plane API and generates
 * TypeScript types for every node's config schema.
 *
 * Usage:
 *   node scripts/codegen-nodes.mjs
 *   API_URL=http://localhost:8088 AUTH_TOKEN=... node scripts/codegen-nodes.mjs
 *
 * Output: src/lib/generated/node-types.ts
 */

import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const API_URL = process.env.API_URL || "http://localhost:8088";
const AUTH_TOKEN = process.env.AUTH_TOKEN || "";
const OUT = resolve(__dirname, "../src/lib/generated/node-types.ts");

function pascalCase(s) {
  return s
    .split(/[_\-\s]+/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
}

function propToTS(prop) {
  if (!prop) return "unknown";
  if (prop.type === "enum" && prop.options)
    return prop.options.map((v) => JSON.stringify(v)).join(" | ");
  if (prop.enum) return prop.enum.map((v) => JSON.stringify(v)).join(" | ");
  switch (prop.type) {
    case "string":
      return "string";
    case "number":
    case "integer":
    case "float":
      return "number";
    case "boolean":
      return "boolean";
    case "array":
      return `${propToTS(prop.items)}[]`;
    case "object":
      return "Record<string, unknown>";
    default:
      return "unknown";
  }
}

function generateInterface(nodeType, entry) {
  const name = `${pascalCase(nodeType)}Config`;
  const schema = entry.config_schema || {};
  const fields = Object.entries(schema)
    .map(([k, v]) => {
      const tsType = propToTS(v);
      const defaultVal =
        v.default !== undefined ? ` // default: ${JSON.stringify(v.default)}` : "";
      return `  ${k}?: ${tsType};${defaultVal}`;
    })
    .join("\n");

  return `export interface ${name} {\n${fields}\n}`;
}

async function main() {
  const url = `${API_URL}/api/v1/nodes`;
  console.log(`Fetching node catalog from ${url} ...`);
  const headers = {};
  if (AUTH_TOKEN) headers["Authorization"] = `Bearer ${AUTH_TOKEN}`;
  const res = await fetch(url, { headers });
  if (!res.ok) {
    console.error(`Failed: ${res.status} ${res.statusText}`);
    process.exit(1);
  }
  const { catalog } = await res.json();
  const entries = Object.entries(catalog);
  console.log(`Got ${entries.length} node types`);

  const interfaces = entries.map(([type, entry]) =>
    generateInterface(type, entry)
  );

  const unionMembers = entries.map(
    ([type]) => `  | { type: "${type}"; config: ${pascalCase(type)}Config }`
  );

  const ioEntries = entries.map(
    ([type, entry]) =>
      `  "${type}": { inputs: ${JSON.stringify(entry.inputs)}, outputs: ${JSON.stringify(entry.outputs)} }`
  );

  const lines = [
    "// Auto-generated by scripts/codegen-nodes.mjs — do not edit",
    "",
    ...interfaces,
    "",
    "export type NodeConfigUnion =",
    unionMembers.join("\n") + ";",
    "",
    "export const NODE_IO: Record<string, { inputs: string[]; outputs: string[] }> = {",
    ioEntries.join(",\n"),
    "};",
    "",
    `export const NODE_TYPES = [${entries.map(([t]) => `"${t}"`).join(", ")}] as const;`,
    "export type NodeType = (typeof NODE_TYPES)[number];",
    "",
  ];

  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, lines.join("\n"));
  console.log(`Wrote ${OUT}`);
}

main();
